//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class liba {
  public static int add(int a, int b, SWIGTYPE_p_f_int_int__int further) {
    int ret = libaPINVOKE.add(a, b, SWIGTYPE_p_f_int_int__int.getCPtr(further));
    return ret;
  }

  public static int add_wrapper(int a, int b, MyCB handler) {
    int ret = libaPINVOKE.add_wrapper(a, b, MyCB.getCPtr(handler));
    return ret;
  }

}
